apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app: reverseproxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy-node
          image: vietanhtwdk/reverseproxy:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8080
